### ISSUE TITLE
Adding a vlan to eth0?

### ISSUE THREAD

**Issue by iyra** [rapidloop/vlan-nats#1]
I'm wondering if it's possible to be able to ping others connected to the NATS server with vlan-nats through my default network interface (eth0) rather than creating a separate one (vnats0). The reason why I am asking is because I wish to play a game that isn't picking up my friend on the vlan, though it does pick up machines which are reachable via my real LAN.

Is there a way I can either have my friend accessible via a 192.168.*.* address, or to redirect such an address to the vnats0 interface? If this is not possible, is there any software (which I can host on a separate server, as I'm behind a firewall) which would allow me to create a virtual LAN on Linux and have machines connected to it accessible via the default network interface?

Thank you.

**Comment by mdevan** [comment]
IP forwarding might help (google for "linux ip forwarding"), depending on what exactly the problem/need is. Otherwise you can setup a VPN on an external server ([like this for example](https://www.digitalocean.com/community/tutorials/how-to-set-up-an-openvpn-server-on-ubuntu-16-04)) and both of you can connect to that.
